services:
  # Backend API Service
  - type: web
    name: qr-scanner-trios-backend
    env: node
    plan: free
    region: oregon
    buildCommand: |
      cd backend
      npm ci --only=production
    startCommand: cd backend && ./start.sh
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://qr-scanner-trios-frontend.onrender.com
      - key: FRONTEND_URL
        value: https://qr-scanner-trios-frontend.onrender.com
      - key: FORCE_SYNC
        value: true
      - key: USE_SQLITE
        value: false
      - key: DB_HOST
        fromDatabase:
          name: qr-scanner-trios-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: qr-scanner-trios-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: qr-scanner-trios-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: qr-scanner-trios-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: qr-scanner-trios-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: qr-scanner-trios-db
          property: connectionString

  # Frontend Web Service (with Express server for SPA routing)
  - type: web
    name: qr-scanner-trios-frontend
    env: node
    plan: free
    region: oregon
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    startCommand: cd frontend && npm run serve
    envVars:
      - key: VITE_API_URL
        value: https://qr-scanner-trios-backend.onrender.com/api

databases:
  - name: qr-scanner-trios-db
    databaseName: qr_ordering_db
    user: qr_ordering_user
    plan: free
    region: oregon
