services:
  - type: web
    name: qr-scanner-trios-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://qr-scanner-trios-backend.onrender.com
      - key: FRONTEND_URL
        value: https://qr-scanner-trios-backend.onrender.com
      - key: FORCE_SYNC
        value: false
