name: Test AWS Credentials

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Test AWS connection
        run: |
          echo "Testing AWS credentials..."
          aws sts get-caller-identity
          echo "✅ AWS credentials are working!"
          
      - name: Test Lightsail access
        run: |
          echo "Testing Lightsail access..."
          aws lightsail get-container-services --region us-east-1
          echo "✅ Lightsail access is working!"
